language: php

dist: trusty

sudo: false

cache:
    directories:
        - ~/.composer/cache

matrix:
    fast_finish: true
    include:
        -   php: 7.2
        -   php: 7.2
            env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
        -   php: 7.3
        -   php: 7.3
            env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

install:
    - composer update --no-interaction --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict
    - composer normalize --dry-run
    - composer check-style
    - composer analyse
    - composer test
